name: Ceedling Unit Tests

on:
  push:
  pull_request:

jobs:
  ceedling-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Install Ceedling
      run: gem install ceedling

    - name: Run Ceedling tests
      working-directory: "Ceedling Tests"
      run: ceedling test:all
